name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '43 23 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is obsolete!'
        stale-pr-message: 'This pull request is obsolete!'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
